# Generated by Django 2.2.3 on 2019-08-01 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('facilitator', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=100)),
                ('home_address', models.CharField(max_length=250, null=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.CharField(max_length=128)),
                ('question_2', models.CharField(max_length=128)),
                ('question_3', models.CharField(max_length=128)),
                ('question_4', models.CharField(max_length=128)),
                ('question_5', models.CharField(max_length=128)),
                ('question_6', models.CharField(max_length=128)),
                ('question_7', models.CharField(max_length=128)),
                ('question_8', models.TextField()),
                ('question_9', models.TextField()),
                ('course_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title', to='feedback.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Entreprenuership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.TextField()),
                ('question_2', models.TextField()),
                ('question_3', models.TextField()),
                ('question_4', models.CharField(max_length=100)),
                ('course_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.Course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.Subject'),
        ),
    ]
